# Generated by Django 4.2 on 2024-06-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elo_rating', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0, editable=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaming.country')),
            ],
            options={
                'ordering': ['-elo_rating'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('result', models.CharField(choices=[('win', 'win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=4)),
                ('black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='gaming.player')),
                ('opening', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaming.opening')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='gaming.player')),
            ],
        ),
    ]
